export const SESSIONS_REQUEST = 'SESSIONS_REQUEST';
export const SESSIONS_RESPONSE = 'SESSIONS_RESPONSE';
export const SESSIONS_FOR_FILM_REQUEST = 'SESSIONS_FOR_FILM_REQUEST';
export const SESSIONS_FOR_FILM_RESPONSE = 'SESSIONS_FOR_FILM_RESPONSE';
export const SERVICES_FOR_SESSION_REQUEST = 'SERVICES_FOR_SESSION_REQUEST';
export const SERVICES_FOR_SESSION_RESPONSE = 'SERVICES_FOR_SESSION_RESPONSE';
