CREATE TABLE [dbo].[Film]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [StartRentDate] DATETIME NOT NULL,
    [EndRentDate] DATETIME NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(300) NOT NULL
)