export const NEW_TICKET_REQUEST = 'SERVICES_FOR_SESSION_REQUEST';
export const NEW_TICKET_RESPONSE = 'SERVICES_FOR_SESSION_RESPONSE';

export const USER_TICKETS_REQUEST = 'USER_TICKETS_REQUEST';
export const USER_TICKETS_RESPONSE = 'USER_TICKETS_RESPONSE';
