export const NEW_TICKET_REQUEST = 'NEW_TICKET_REQUEST';
export const NEW_TICKET_RESPONSE = 'NEW_TICKET_RESPONSE';
export const NEW_TICKET_REQUEST_FAIL = 'NEW_TICKET_REQUEST_FAIL';

export const TICKET_PAY_REQUEST = 'TICKET_PAY_REQUEST';
export const TICKET_PAY_RESPONSE = 'TICKET_PAY_RESPONSE';

export const USER_TICKETS_REQUEST = 'USER_TICKETS_REQUEST';
export const USER_TICKETS_RESPONSE = 'USER_TICKETS_RESPONSE';
